version: "3"
services:
  auth-service_container:
    build: ./verification/
    ports:
      - '55442:80'
    volumes:
      - ./:/app
  redis_container:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
  mongodb_container:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/ProjectA/:/data/db/
